#!/usr/bin/groovy
pipeline {
	agent any

	    stages {

		stage('CheckoutSCM') {
			steps {
				echo 'Building..'
			}
		}




        stage('Git Checkout') {
			steps {
				echo 'Testing..'
			}
		}




		stage('Python Unit Test') {
			steps {
				echo 'Testing..'
			}
		}



		stage('SonarQube') {
			steps {
				echo 'Testing..'
			}
		}

stage('Dependecy Check') {
			steps {
				echo 'Testing..'
			}
		}

		stage('Fority Python') {
			steps {
				echo 'Testing..'
			}
		}


		stage('Fortify JavaScript') {
			steps {
				echo 'Testing..'
			}
		}


		stage('CloudFormation') {
			steps {
				echo 'Testing..'
			}
		}


		stage('Cypress') {
			steps {
				echo 'Testing..'
			}
		}

		stage('Arachni') {
			steps {
				echo 'Testing..'
			}
		}

		stage('Cleanup') {
			steps {
				echo 'Testing..'
			}
		}






		stage('Email') {
			steps {
				echo 'Testing..'
			}
		}

		stage('Deploy') {
			steps {
				echo 'Deploying....'
			}
		}

	}
}
